remote_theme: WildCodeSchool/workshops-jekyll-theme

# disable the jekyll-titles-from-headings plugin, 
# so first h1 will not be used as prior title of you page
titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # possible values: default or tic-tac

style: dev # possible values: dev, data, ciber, design or wild.
title: 'Atelier introduction à PHP'
description: 'Découvrir les bases du langage PHP et réaliser un premier formulaire de contact.'
# type: ''
main_image: 'images/fantasy-2995326_1920.jpg' # http or relative path to image
show_clone: false
show_toc: true
lang: fr